"use strict";

/**
 * Farm Animals — cur-lp-preschool-farm-animals
 * Preschool Free published. Enrichment draft only.
 * Preserve Free / published. Do not touch Farm Friends toddler Pro twin.
 */

const PLAN_ID = "cur-lp-preschool-farm-animals";
const FARM_FRIENDS_TWIN = "cur-lp-toddler-farm-friends";

function base(extra) {
  return {
    ageModifications: "Preschool",
    decision: "improve",
    imagePlan: "IMAGE_NOT_NEEDED",
    imageRequirement: "not_needed",
    indoorAlternatives: "Designed for indoor classroom centers.",
    outdoorAlternatives: "Move sorting, market, or wash play outdoors when weather allows.",
    mixedAgeAdaptations: "Younger preschoolers need fewer choices; older preschoolers lead tours and explain sorts.",
    ...extra,
  };
}

const week = {
  weeklyOverview:
    "Preschoolers investigate how farm animals move, communicate, live, and help people — through discovery baskets, sound/movement, sorting, sensory wash play, STEM shelters, market dramatic play, counting, process art, and a collaborative class farm.",
  objectives: [
    "Name common farm animals and match simple sounds/movements",
    "Sort animals by habitat or what they provide and explain one choice",
    "Count farm items with one-to-one correspondence",
    "Build a simple animal shelter and test fit/stability",
    "Use farm vocabulary in play, songs, and storytelling",
    "Practice gentle animal-care routines and turn-taking",
  ].join("\n"),
  weeklyMaterials: [
    "Washable farm animal figures; discovery basket; magnifiers",
    "Habitat mats / picture cards (barn, pond, field)",
    "Play dough or wash bins, brushes, towels, smocks",
    "Blocks, cardboard, tape for shelters",
    "Market props: baskets, play food, egg cartons, play coins",
    "Rubber glove milking station; plastic eggs; egg cartons",
    "Large mural paper; washable paint; animal track stamps/feet",
    "Farm Animals Picture Card Pack (linked printable)",
  ].join("\n"),
  teacherPreparation: [
    "Stage one invitation at a time; cover tables for wash/paint",
    "Print/cut picture cards; prep habitat mats",
    "Test milking glove outdoors or over towels",
    "Clear floor lane for movement trail; secure mural paper",
  ].join("\n"),
  familyConnection:
    "Invite families to share a farm visit photo or favorite animal sound. Suggest counting eggs or sorting toy animals at home — no worksheets required.",
  observationFocus: [
    "Names animals / sounds",
    "Sorts and explains",
    "Counts with one-to-one",
    "Persists with building/care play",
    "Uses farm vocabulary",
  ].join("\n"),
  books: [
    { title: "Big Red Barn", author: "Margaret Wise Brown", notes: "Barn rest / animal sounds — keep interactive." },
    { title: "Click, Clack, Moo: Cows That Type", author: "Doreen Cronin", notes: "Humor + farm jobs talk; shorten if needed." },
    { title: "Farm Animals", author: "Roger Priddy", notes: "Photo vocabulary support." },
  ],
  songs: [
    {
      title: "Old MacDonald Had a Farm",
      notes: "Public-domain style; use props for each verse.",
      rightsStatus: "traditional_public_domain",
    },
    {
      title: "The Farmer in the Dell",
      notes: "Circle dance; offer seated participation.",
      rightsStatus: "traditional_public_domain",
    },
    {
      title: "B-I-N-G-O",
      notes: "Clap syllables; listening focus.",
      rightsStatus: "traditional_public_domain",
    },
  ],
  milestones: ["Language", "Cognition", "Fine Motor", "Gross Motor", "Social Emotional", "Creativity"],
  vocabCards: ["farm", "barn", "cow", "pig", "chicken", "horse", "sheep", "egg", "milk", "mud", "shelter", "market"],
  teacherToolkit: {
    prepChecklist: [
      "Picture cards cut",
      "Wash/paint covers ready",
      "Shelter materials sorted",
      "Market props stocked",
    ],
    observationFocus: [
      "Animal naming",
      "Sorting language",
      "Careful tool use",
    ],
    teacherPreparation: "Protect process play — celebrate building, washing, and storytelling over perfect products.",
  },
};

const activities = {
  "Farm Animal Discovery Basket": base({
    decision: "keep",
    imagePlan: "IMAGE_REQUIRED",
    imageRequirement: "required",
    reuseExistingSetupImage: true,
    keepExampleImage: false,
    activityCategory: "Open-Ended Exploration",
    durationMinutes: 15,
    objective: "Closely observe, name features, and compare at least two farm animals.",
    description: "Children explore a basket of farm figures and textures, then build and narrate a small farm scene.",
    materials: ["Basket", "Washable farm animals", "Fabric/felt textures", "Fabric eggs", "Magnifiers", "Picture cards (optional)"],
    preparation: "Sanitize figures; stage basket on low table with magnifiers.",
    setup: "Low table or mat with discovery basket and 2–3 magnifiers.",
    steps: [
      "Choose an animal",
      "Observe covering, feet, face, and size",
      "Name or imitate it",
      "Compare two animals",
      "Build a small scene and tell what happens",
    ],
    teacherLanguage: "What do you notice?\nHow are they alike or different?\nWhere might it live?",
    observationOpportunities: "Names, attributes, comparisons, shared-play language.",
    safetyNotes: "Large washable pieces; supervise mouthing; check allergies to hay/felt.",
    cleanupTips: "Match animals to labeled basket; wipe figures.",
    teacherTips: ["Do not quiz; accept home-language names and sounds."],
    vocabulary: ["farm", "barn", "soft", "bump", "same", "different"],
    imageBriefSetup: "Preschool discovery basket with farm animals, textures, magnifiers on a low classroom table.",
  }),

  "Farm Sound & Motion Circle": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Music & Movement",
    durationMinutes: 10,
    objective: "Match farm animal sounds and simple motions in a group circle.",
    description: "Sing Old MacDonald (or similar); children pick props and move/sound like the animal.",
    materials: ["Animal props or picture cards", "Open circle space"],
    preparation: "Gather 5–6 props; post verse order if helpful.",
    setup: "Circle rug with prop basket in center.",
    steps: [
      "Sing the opening together",
      "One child picks an animal",
      "Group sings that verse with sound",
      "Add a simple motion",
      "Return prop and continue",
    ],
    teacherLanguage: "What sound does your animal make?\nHow does it move?",
    observationOpportunities: "Sound matching; participation; turn-taking.",
    safetyNotes: "Clear space; no running in circle.",
    cleanupTips: "Return props to basket.",
    vocabulary: ["moo", "oink", "cluck", "farmer", "sing"],
  }),

  "Barnyard Movement Trail": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Gross Motor",
    durationMinutes: 10,
    objective: "Move across a lane using farm-animal locomotor patterns.",
    description: "Children draw an animal card and stomp, trot, waddle, or gallop across a clear path.",
    materials: ["Animal picture cards", "Clear walking lane", "Optional cones"],
    preparation: "Clear lane; stack cards face-down.",
    setup: "One-way movement path with start/finish markers.",
    steps: [
      "Draw an animal card and name it",
      "Move across the lane like that animal",
      "Freeze at the end",
      "Walk back and choose again",
      "Rest and stretch",
    ],
    teacherLanguage: "Can you stomp like a horse?\nWaddle like a duck!",
    observationOpportunities: "Body control; following directions; animal vocabulary.",
    safetyNotes: "No collisions; one direction; soft landings.",
    vocabulary: ["stomp", "trot", "waddle", "gallop", "freeze"],
  }),

  "Where Does It Belong? Farm Sorting": base({
    decision: "improve",
    imagePlan: "IMAGE_HELPFUL",
    imageRequirement: "optional",
    activityCategory: "Fine Motor",
    durationMinutes: 12,
    objective: "Sort farm animals by habitat (or product) and explain one placement.",
    description: "Children place figures on barn/pond/field mats and count each group.",
    materials: ["Habitat mats or cards", "Farm animal figures", "Simple rule card"],
    preparation: "Label mats; limit to 8–10 animals.",
    setup: "Table with 2–3 mats and animal basket.",
    steps: [
      "Name today’s sort rule",
      "Pick one animal and talk about where it lives",
      "Place it on the mat",
      "Count each group",
      "Resort with a new rule if time allows",
    ],
    teacherLanguage: "Where does this animal belong?\nHow do you know?",
    observationOpportunities: "Sorting logic; explaining; counting.",
    safetyNotes: "Large figures only.",
    cleanupTips: "Return animals to basket; stack mats.",
    vocabulary: ["sort", "barn", "field", "pond", "same", "different"],
    supportAdaptations: "Offer two mats only; model one sort aloud.",
    addedChallenge: "Sort by product (milk/eggs/wool) for a second round.",
    imageBriefSetup: "Preschool farm sorting table with habitat mats and animal figures — candid classroom setup photo, not a printable sheet.",
  }),

  "Muddy Animals Wash Laboratory": base({
    decision: "improve",
    imagePlan: "IMAGE_REQUIRED",
    imageRequirement: "required",
    reuseExistingSetupImage: true,
    keepExampleImage: false,
    activityCategory: "STEM/Discovery",
    durationMinutes: 15,
    objective: "Explore muddy/wash sensory play while practicing gentle animal care motions.",
    description: "Children wash muddy farm figures in soapy water with sponges and brushes, then dry them.",
    materials: ["Two bins (muddy animals + soapy water)", "Sponges", "Soft brushes", "Towels", "Smocks"],
    preparation: "Coat a few washable figures with washable “mud”; fill wash bin; cover table.",
    setup: "Wash lab with muddy bin, wash bin, and drying towel.",
    steps: [
      "Choose a muddy animal",
      "Wash with sponge or brush",
      "Rinse and watch the water change",
      "Dry on the towel",
      "Wash hands",
    ],
    teacherLanguage: "What happened to the mud?\nHow can we be gentle?",
    observationOpportunities: "Sensory tolerance; fine motor; care language.",
    safetyNotes: "Washable paint/mud only; supervise water; no tasting.",
    cleanupTips: "Dump water; rinse figures; wipe table.",
    substitutions: ["Brown play dough mud if water play is unavailable"],
    vocabulary: ["mud", "wash", "scrub", "rinse", "clean"],
    imageBriefSetup: "Two-bin muddy animal wash station with sponges and towels in a preschool classroom.",
  }),

  "Build an Animal Shelter STEM Challenge": base({
    decision: "improve",
    imagePlan: "IMAGE_REQUIRED",
    imageRequirement: "required",
    reuseExistingSetupImage: true,
    keepExampleImage: false,
    activityCategory: "STEM/Discovery",
    durationMinutes: 15,
    objective: "Plan and build a shelter that fits a chosen farm animal and stands on its own.",
    description: "Children use blocks, cardboard, and tape to build shelters, then test fit and stability.",
    materials: ["Blocks", "Cardboard pieces/boxes", "Tape", "Farm animals", "Optional shelter photo prompts"],
    preparation: "Sort materials into baskets; remove staples; set animal lineup.",
    setup: "STEM table with material baskets and animals at the front.",
    steps: [
      "Choose an animal and name what it needs",
      "Select materials",
      "Build a shelter",
      "Test fit, entry, and stability",
      "Revise and share",
    ],
    teacherLanguage: "Does your animal fit?\nWhat happens if we push gently?",
    observationOpportunities: "Planning; testing; revising; vocabulary (shelter, fence, roof).",
    safetyNotes: "Lightweight materials; supervise scissors/tape; no climbing on builds.",
    cleanupTips: "Flatten cardboard; return blocks.",
    teacherTips: ["Celebrate rebuilds — falling is part of STEM."],
    vocabulary: ["shelter", "roof", "wall", "fit", "strong"],
    imageBriefSetup: "Preschool STEM table with cardboard, blocks, tape, and farm animals for shelter building.",
  }),

  "Preschool Farmers Market": base({
    decision: "improve",
    imagePlan: "IMAGE_HELPFUL",
    imageRequirement: "optional",
    activityCategory: "Dramatic Play",
    durationMinutes: 15,
    objective: "Practice farmer/customer roles while counting items and using polite language.",
    description: "Children stock a market stand, buy with play coins, and switch roles.",
    materials: ["Market stand/table", "Baskets", "Pretend produce", "Egg cartons", "Play coins", "Role necklaces optional"],
    preparation: "Stock stand; post a simple picture price list (1–3 coins).",
    setup: "Dramatic-play market with farmer/customer roles.",
    steps: [
      "Farmers stock the stand",
      "Customers greet and choose items",
      "Count items and coins",
      "Say thank you",
      "Switch roles and restock",
    ],
    teacherLanguage: "How many coins?\nWhat are you selling today?",
    observationOpportunities: "Counting; role language; turn-taking.",
    safetyNotes: "No real food allergies; large props only.",
    vocabulary: ["market", "farmer", "customer", "buy", "sell", "thank you"],
    imageBriefSetup: "Preschool dramatic-play farmers market stand with baskets, produce props, and play coins — classroom photo, not a printable sheet.",
  }),

  "Pretend Milking Fine-Motor Station": base({
    decision: "improve",
    imagePlan: "IMAGE_REQUIRED",
    imageRequirement: "setup_only",
    activityCategory: "Fine Motor",
    durationMinutes: 10,
    objective: "Strengthen hands by squeezing a glove milking station and watching drips collect.",
    description: "Children take short turns squeezing a water-filled rubber glove with pinholes into a bucket.",
    materials: ["Rubber glove with tiny pinholes", "Bucket", "Towels", "Optional cow photo"],
    preparation: "Adult prepares, secures, and tests glove over towels.",
    setup: "One-child milking station with towels under bucket.",
    steps: [
      "Teacher models a gentle squeeze",
      "Child squeezes glove fingers",
      "Watch drips into the bucket",
      "Talk about milk and dairy foods",
      "Dry hands and wipe spills",
    ],
    teacherLanguage: "Squeeze gently… drip!\nWhat foods come from milk?",
    observationOpportunities: "Grip strength; patience; vocabulary.",
    safetyNotes: "Adult-prepared only; supervise water; no sharing mouth contact.",
    cleanupTips: "Empty glove/bucket; sanitize; dry towels.",
    vocabulary: ["milk", "cow", "squeeze", "drip", "dairy"],
    imageBriefSetup: "Preschool pretend milking station with rubber glove over a bucket and towels in a classroom.",
  }),

  "From Farm to Table Story Investigation": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Literacy",
    durationMinutes: 12,
    objective: "Connect a farm story to foods/products animals provide.",
    description: "Read Big Red Barn (or similar) with props; discuss farm-to-table ideas briefly.",
    materials: ["Farm book", "A few animal props"],
    preparation: "Preview book; choose 2–3 stop-and-talk pages.",
    setup: "Circle so all can see pictures.",
    steps: [
      "Ask what animals might sleep in a barn",
      "Read with animal sounds",
      "Pause to name a product (milk/eggs)",
      "Retell with props",
      "Close with one farm-to-table idea",
    ],
    teacherLanguage: "What did the animals do?\nWhat food might come from this animal?",
    observationOpportunities: "Listening; retell; product vocabulary.",
    vocabulary: ["barn", "story", "milk", "egg", "farm"],
  }),

  "Egg Collection Counting Challenge": base({
    decision: "improve",
    imagePlan: "IMAGE_HELPFUL",
    imageRequirement: "optional",
    activityCategory: "Open-Ended Exploration",
    durationMinutes: 12,
    objective: "Collect and count eggs with one-to-one correspondence to a numeral.",
    description: "Children fill egg cartons or cups labeled 1–10 with plastic eggs and check their count.",
    materials: ["Plastic eggs", "Egg cartons or numeral cups", "Tray"],
    preparation: "Prep 1–5 set and optional 6–10 challenge set.",
    setup: "Counting station with eggs in a tray and labeled cartons.",
    steps: [
      "Read the numeral",
      "Place that many eggs",
      "Touch-count to check",
      "Empty and try a new numeral",
      "Compare which has more",
    ],
    teacherLanguage: "How many eggs?\nWhich cup has more?",
    observationOpportunities: "One-to-one counting; numeral recognition; comparing.",
    safetyNotes: "Large plastic eggs only.",
    vocabulary: ["count", "egg", "more", "less", "same"],
    imageBriefSetup: "Preschool egg counting station with plastic eggs and numeral egg cartons on a classroom table.",
  }),

  "Collaborative Animal-Track Mural": base({
    decision: "improve",
    imagePlan: "IMAGE_HELPFUL",
    imageRequirement: "example_only",
    reuseExistingSetupImage: true,
    keepExampleImage: true,
    activityCategory: "Art",
    durationMinutes: 15,
    objective: "Make animal tracks on a shared mural and narrate a short farm story.",
    description: "Children walk/hop animal figures or stamps through paint to leave tracks on large paper.",
    materials: ["Large paper", "Washable paint", "Animal figures or track stamps", "Smocks"],
    preparation: "Tape paper securely; thin paint; dry path ready.",
    setup: "Mural table/wall with paint trays and animals.",
    steps: [
      "Predict what marks animals might make",
      "Walk/hop animals through paint onto paper",
      "Compare pressure and direction",
      "Add grass/barn details after drying starts",
      "Tell a track story together",
    ],
    teacherLanguage: "Whose tracks are these?\nWhat happened on our farm?",
    observationOpportunities: "Cause-effect; collaboration; storytelling.",
    safetyNotes: "Washable paint; smocks; supervise paint trays.",
    cleanupTips: "Wipe animals; hang mural to dry.",
    vocabulary: ["track", "print", "stamp", "mural", "farm"],
    imageBriefSetup: "Children making animal tracks on a large classroom farm mural with washable paint.",
  }),

  "Grooming and Caring for Animals": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Social Emotional",
    durationMinutes: 10,
    objective: "Practice gentle care routines with plush animals and soft brushes.",
    description: "Children brush plush horses/animals and use soft voices during care play.",
    materials: ["Plush farm animals", "Soft brushes", "Small towels"],
    preparation: "Set a calm table away from high traffic.",
    setup: "Care station with 2–3 plush animals.",
    steps: [
      "Choose an animal",
      "Brush gently",
      "Talk softly to the animal",
      "Towel dry",
      "Put animal to rest",
    ],
    teacherLanguage: "How can we be gentle?\nWhat does your animal need?",
    observationOpportunities: "Gentle touch; empathy language.",
    vocabulary: ["gentle", "brush", "care", "soft"],
  }),

  "Mystery Farm Sound Game": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Open-Ended Exploration",
    durationMinutes: 10,
    objective: "Listen to a farm sound and cover the matching animal on a simple card.",
    description: "Teacher plays or makes animal sounds; children cover matches on bingo-style cards.",
    materials: ["Simple farm bingo cards", "Tokens", "Sound cues or teacher voice"],
    preparation: "Prep cards with 4–6 animals; practice cues.",
    setup: "Seated group with cards and tokens.",
    steps: [
      "Explain cover-the-match",
      "Play/make an animal sound",
      "Children cover the match",
      "Name the animal together",
      "Continue until cards are full",
    ],
    teacherLanguage: "What did you hear?\nFind the match!",
    observationOpportunities: "Listening; matching; vocabulary.",
    vocabulary: ["listen", "match", "sound", "same"],
  }),

  "Barnyard Story and Movement Celebration": base({
    decision: "keep",
    imagePlan: "IMAGE_NOT_NEEDED",
    activityCategory: "Music & Movement",
    durationMinutes: 10,
    objective: "Celebrate the week with a farm circle dance and shared animal favorites.",
    description: "Dance The Farmer in the Dell (or similar); share favorite animals from the week.",
    materials: ["Open circle space", "Optional talking prop"],
    preparation: "Cue song; clear space.",
    setup: "Circle dance area.",
    steps: [
      "Form a circle",
      "Dance the verses",
      "Switch farmer/partner roles",
      "Share a favorite animal",
      "Bow and cheer",
    ],
    teacherLanguage: "Who was the farmer?\nWhat was your favorite animal this week?",
    observationOpportunities: "Participation; recall; joy.",
    vocabulary: ["circle", "farmer", "partner", "favorite"],
  }),

  "Design Our Class Farm": base({
    decision: "improve",
    imagePlan: "IMAGE_HELPFUL",
    imageRequirement: "example_only",
    reuseExistingSetupImage: true,
    keepExampleImage: true,
    activityCategory: "STEM/Discovery",
    durationMinutes: 20,
    objective: "Collaborate to build a class farm scene and lead a short tour.",
    description: "Children add barns, fences, ponds, and animals to a shared farm base, then give a tour.",
    materials: ["Large base paper/box lids", "Cardboard", "Blocks", "Tape", "Farm animals", "Paper pond/grass scraps"],
    preparation: "Stage materials; clear a large table.",
    setup: "Collaborative build table with sorted materials.",
    steps: [
      "Revisit favorite week ideas",
      "Choose an area to build (barn, pen, pond)",
      "Build and connect spaces",
      "Place animals and test movement paths",
      "Lead a tour for friends",
    ],
    teacherLanguage: "What does our farm need next?\nCan you show us the chicken coop?",
    observationOpportunities: "Collaboration; planning; vocabulary; pride.",
    safetyNotes: "Lightweight builds; supervise tape/scissors.",
    cleanupTips: "Photo the farm; send pieces home or store flat.",
    vocabulary: ["barn", "fence", "pond", "coop", "tour"],
    imageBriefSetup: "Preschoolers and teacher building a collaborative classroom farm with cardboard, blocks, and animals.",
  }),
};

module.exports = {
  planId: PLAN_ID,
  title: "Farm Animals",
  ageLabel: "Preschool ages approximately 3–5 years",
  expectedPlan: "Free",
  expectedStatus: "published",
  allowSameTitleDifferentAgeOrStatus: false,
  forbidTouchPlanIds: [FARM_FRIENDS_TWIN],
  week,
  activities,
  imageCoverPreference: [
    "Farm Animal Discovery Basket",
    "Design Our Class Farm",
    "Build an Animal Shelter STEM Challenge",
    "Muddy Animals Wash Laboratory",
    "Collaborative Animal-Track Mural",
  ],
  printables: {
    keepResourceIds: ["cur-res-c5cd1e5e6d5ea78a"],
    create: [],
    notes: [
      {
        title: "Farm Animals Preschool Picture Card Pack",
        id: "cur-res-c5cd1e5e6d5ea78a",
        decision: "KEEP",
        pages: 5,
        why: "Clean preschool animal cards teachers actually print for sorting, dramatic play, and vocabulary — complements centers without filler worksheets.",
      },
    ],
  },
};
